export const SET_USER_NAME = "SET_USER_NAME"
export const ADD_EXPERIMENT = "ADD_EXPERIMENT"
export const GET_ALL = "GET_ALL"

export const GET_EXPERIMENTS = 'GET_EXPERIMENTS'
export const GET_EXPERIMENTS_SUCCESS = 'GET_EXPERIMENTS_SUCCESS'
export const GET_EXPERIMENTS_FAILURE = 'GET_EXPERIMENTS_FAILURE'

export const GET_EXPERIMENT = 'GET_EXPERIMENT'
export const GET_EXPERIMENT_SUCCESS = 'GET_EXPERIMENT_SUCCESS'
export const GET_EXPERIMENT_FAILURE = 'GET_EXPERIMENT_FAILURE'

export const SET_LOGGED_IN_STATUS = 'SET_LOGGED_IN_STATUS'

export const SET_API_KEY = 'SET_API_KEY'
export const GET_API_KEYS = 'GET_API_KEYS'

export const LIST_JOBS = 'LIST_JOBS'
export const CREATE_JOB = 'CREATE_JOB'

export const REMOVE_JOB = 'REMOVE_JOB'
export const GET_EXECUTABLE = 'GET_EXECUTABLE'